version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    volumes:
      - .:/user/app
    ports:
      - 3000:3000
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
