version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    volumes:
      - .:/user/app
    ports:
      - 3000:3000
    depends_on:
      - mongo_db
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/fuul-db?retryWrites=true&w=majority

volumes:
  mongo_db: {}
